CREATE DATABASE b3case;

\c b3case;

CREATE TABLE "Order" (
    Id SERIAL PRIMARY KEY NOT NULL,
    Description VARCHAR(200) NOT NULL,
    Status VARCHAR(200) NOT NULL,
    Date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);